### ISSUE TITLE
log4q: single-character namespaces are reserved for use by Kx

### ISSUE THREAD

**Issue by ghost** [prodrive11/q_stuff#2]
The log4q script uses namespace `.l` but [Kx reserves single-character namespaces for its own use](http://code.kx.com/q/ref/card/#namespaces).

Some suitable alternatives: `.log`, `.l4q`, or `.log4q`

**Comment by prodrive11** [comment]
A bit long option, but .log4q will be concise with the filename, and naming convention for other languages.
